### ISSUE TITLE
Cannot type in text fields after dismissing a pop-up prompt

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-desktop#188] opened 2021-04-02 18:59 UTC
### Expected Behavior

Text fields in the Scratch editor always work

### Actual Behavior

Text fields in the editor will not accept focus after dismissing the "Replace contents of the current project?" dialog with either "OK" or "Cancel" or dismissing the "Leave Scratch?" prompt with "Stay"

### Steps to Reproduce

1. Start the app
2. Make a change, such as moving the cat sprite
3. Use any of these ways to cause a popup prompt, then dismiss it:
   * "File -> New" and pick either "OK" or "Cancel"
   * "File -> Load from your computer" and pick either "OK" or "Cancel"
   * Attempt to close the app and pick "Stay"
5. Attempt to change the project title or type into any text field

Once in this state, choosing "File -> Load from your computer" and picking "Cancel" will fix it.

### Operating System and Browser

This issue seems to affect Windows only.

**Comment by apple502j** [comment] 2021-04-03 05:00
Duplicate of #112

**Comment by BryceLTaylor** [comment] 2021-04-08 18:43
Closing as duplicate of #112

**Closed as completed by BryceLTaylor** 2021-04-08 18:43 UTC
