### ISSUE TITLE
file assiciation?

### ISSUE THREAD

**Issue by jeffalo** [LLK/scratch-desktop#116] opened 2020-05-21 15:55 UTC
### Expected Behavior

double clicking an sb3 file opens scratch desktop on that file

### Actual Behavior

it doesnt

### Steps to Reproduce

double click an sb3 file

### Operating System and Browser

windows 10 chrome

Perhaps scratch-desktop could be the default associated app for sb3 files so that you don't have to open it up first.

**Comment by apple502j** [comment] 2020-05-21 15:59
Duplicate of #32

**Closed as completed** 2020-05-21 19:58 UTC
