### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by mkovalevski** [LLK/scratch-desktop#156] opened 2020-10-04 20:58 UTC
I develop an extension for arduino and when I call a window, which is created by myself, with .html file I get such error in production mode (desktop version): `Not allowed to load local resource: file:///C:/Users/User/AppData/Local/Programs/Scratch Desktop/resources/app.asar/port-window.html`

I call this window in renderer.jsx file and my port-window.html located in the same directory with renderer.jsx
```
                let portWindow = new BrowserWindow({
                    width: 400,
                    height: 250,
                    frame: true,
                });`

                portWindow.loadURL(url.format({
                    slashes: true,
                    protocol: 'file:',
                    pathname: path.join(__dirname, 'port-window.html'),
                }));
```
Does somebody know how to fix it?

**Comment by BryceLTaylor** [comment] 2020-10-08 21:02
duplicate of https://github.com/LLK/scratch-gui/issues/6236

**Closed as completed by BryceLTaylor** 2020-10-08 21:02 UTC
Labels: question

**Comment by cwillisf** [comment] 2020-10-16 21:30
Hi @happy228!
Since we don't officially support doing this kind of thing I'm going to leave this issue closed, but I'll try to help if I can.
I suspect the problem is that your `port-window.html` file is not making it into the bundle. You'll need to adjust the webpack configuration to include the file, and depending on how you do that you might or might not need to adjust the path between different kinds of builds (packaged vs. not packaged, etc.).

If you don't need to run `webpack` on `port-window.html` you might be able to just add a `CopyWebpackPlugin` entry for it in `webpack.renderer.js`, but if you do need to run `webpack` then things are going to get complicated. Unfortunately `electron-webpack` doesn't support multiple entry points last I checked, so you may need to add `port-window.html` to the routing rules in `src/renderer/index.js`.
