### ISSUE TITLE
You should be able to open a file directly.

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-desktop#132] opened 2020-07-27 19:59 UTC
When double clicking on a.sb3 file it should open up in scratch desktop. Instead it just opens a blank file in scratch desktop and you still need to load the file you wanted "from your computer". This is time consuming and inefficient. I also don't remember if I had to corner click and do "always open with scratch desktop" or not.

**Comment by BryceLTaylor** [comment] 2020-07-27 21:03
This is a duplicate of https://github.com/LLK/scratch-desktop/issues/32

**Closed as completed by BryceLTaylor** 2020-07-27 21:03 UTC
